// This file is auto-generated by the JavaScript build process.
// You can add your own controller registrations here if needed.

import { application } from "./application"

import ColumnViewController from "./column_view_controller"
application.register("column-view", ColumnViewController)

// Import and register other controllers as needed...
